# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrinKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'FBSDKLoginKit'
  pod 'SwiftInstagram', '~> 1.1.1'
  # Pods for DrinKit

  target 'DrinKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrinKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
